export const LENDERS_LIST = [
  "Aadhar Housing Finance",
  "Aditya Birla Housing Finance",
  "Ambit Finvest",
  "Anand Rathi Global Finance Limited",
  "Arka Fincap Ltd",
  "Ashok Leyland Finance",
  "AU Small Finance Bank Limited",
  "Axis Bank",
  "Axis Finance",
  "Bajaj Finance Ltd",
  "Bandhan Bank",
  "Bank of Baroda",
  "Bank of Maharashtra",
  "Bee Fintech Pvt Ltd - Incread",
  "Capital First",
  "Capital Float",
  "Capri Global",
  "Catholic Syrian Bank (CBS)",
  "Centrum  Financial Services Ltd (Unity Small Finance Bank Ltd)",
  "Cholamandalam",
  "Citibank N A",
  "Clix Capital Services Pvt Ltd",
  "DBS Bank Ltd",
  "DCB",
  "Deutsche",
  "Dhanvarsha Finvest Limited (Trucap Finance Ltd)",
  "Digicredit (SME Corner)",
  "Easy Home Finance Ltd",
  "Edelweiss Housing Finance",
  "Essel Finance Ltd",
  "Federal Bank",
  "Fedbank Financial Services Pvt Ltd",
  "First Blue",
  "Fullerton India Credit Company Ltd",
  "Growth Source Financial Services (Protium Finance Lrd)",
  "HDB Financial Services",
  "Hero Fin Corp",
  "Hinduja Housing Finance Ltd",
  "HSBC",
  "ICICI HomeFinance Ltd",
  "IDFC Bank Ltd",
  "IndiaBulls",
  "Indiainfoline",
  "Indostar Capital Ltd",
  "Indusind Bank",
  "Indian Overseas Bank  (IOB)",
  "J M  Financial",
  "Jana Small Finance Pvt Ltd",
  "The Karur Vysva Bank Limited",
  "Karvy",
  "Kotak Mahindra bank",
  "Kotak Mahindra Prime",
  "L & T Housing Finance Ltd",
  "LIC Housing Finance",
  "Magma Finance Ltd",
  "Mahindra & Mahindra Financial Services Limited",
  "MAS Financial Services Pvt Ltd",
  "Mathew Easow Research  Securities Pvt Ltd (MERSL)",
  "Moneywise Financial Services Pvt Ltd (SMC Finance)",
  "Motilal Oswal Home Finance Ltd",
  "Muthoot Housing  Finance Ltd",
  "Orix Leasing and Financial Services Pvt Ltd",
  "Piramal Housing Finance",
  "PNBHFL",
  "Poonawala Housing Finance",
  "Punjab National Bank (PNB)",
  "RattanIndia Finance Ltd",
  "Reliance",
  "Repco Home Finance Ltd",
  "SBI",
  "SBM (State Bank of Mariutius)",
  "SCB",
  "Standard Chartered Investments and Loans India Ltd",
  "Shriram City",
  "Shriram Union City Finance",
  "Shriram Finance Ltd",
  "Shinhan Bank",
  "Shubham Housing Finance",
  "South Indian Bank",
  "Sundaram BNP Paribas Home Loan Limited",
  "TVS Credit Services Ltd",
  "Ugrow Capital Limited",
  "Ujivan Small Finance Bank Limited",
  "United Bank of India",
  "Unity Small Finance Bank Ltd",
  "Utkarsh  Small Finance Bank Ltd",
  "Vastu Housing Finance Corporation Ltd.",
  "Vistaar Financial Services Pvt Limited",
  "Yes Bank",
  "Zen Lefin Pvt Ltd (Capital Float)",
  "Aavas Financiers Limited (AU housing Finance)",
  "Bajaj Housing Finance Ltd",
  "Bank of India (BOI)",
  "Capital First Home Finance Ltd",
  "Capital India Home Loans Ltd",
  "Central Bank of India (CBI)",
  "Clix Housing Finance Ltd",
  "DMI Housing Finance",
  "Doha Bank QPSC",
  "Fulletron India Home Finance Company Ltd",
  "Godrej Housing Finance Ltd",
  "Hero Housing Finance",
  "Indian Bank",
  "Indostar Home Finance Pvt Ltd (IHFPL)",
  "J M Financial Home Loans",
  "Khush Housing Finance Ltd (KHFL)",
  "Magma Housing Finance Ltd",
  "Mahindra Rural Housing Finance",
  "Mahindra Home Finance Ltd",
  "Navi Finserv Pvt Ltd",
  "RBL Bank",
  "Religare housing Development Finance Corp Ltd",
  "Shriram Housing Finance",
  "Suryoday Small Finance Bank Ltd",
  "Tata Capital Housing Finance Limited",
  "Union Bank of India",
  "Ummeed Housing Finance",
  "Aditya Birla Finance",
  "APAC Financial Services Private Limited",
  "Avanse Financial Services Ltd",
  "Blue Jay Finlease Pvt Ltd (Zip Loan)",
  "Clix Finance India Private Limited",
  "Coin Tribe Technologies Pvt Ltd",
  "Credit (Kisetsu) Saison India Ltd",
  "Customer SME",
  "Ditya Finance Pvt Ltd (Mcapital)",
  "EDELWEISS RETAIL FINANCE LTD",
  "Equitas",
  "Equifax Fintech",
  "Finmax Credit and Finance Pvt Ltd",
  "Finnovation Tech Solutions Private Limited - Kreditbee",
  "Flexiloans Technologies Pvt Ltd",
  "Ganesh Leasfin Private Ltd",
  "HDFC BANK LTD",
  "Home Credit india Private Ltd",
  "ICICI Bank Ltd.",
  "Indiabulls",
  "Indiabulls Rural Finance Private Limited",
  "INDIFI",
  "Insta Capital Pvt Lrd",
  "Ashv  Finance Limited (Jain Son Finlease Ltd)",
  "JRG Fincorp Ltd - (Indi Trade)",
  "L & T Finance",
  "Aadri Infin Ltd (lendingkart)",
  "Magma Finance Ltd (Poonawala)",
  "Manapuram Finance Ltd",
  "Mangal Fincorp",
  "Neogrowth",
  "Niyogin",
  "Piramal Capital and Housing Finance Ltd",
  "Poonawala Finance",
  "Poonawala fincorp",
  "Profectus Capital",
  "Ratnakar Bank Ltd",
  "Religare",
  "Satin Housing Finance Ltd",
  "SBI PL",
  "Shivaik Mercantile Co-op Bank Ltd",
  "Tata Capital Financial Services Limited",
  "Transunion CIBIL",
  "Ugro Capital Limited",
  "United Petro Finance Limited (Fortune Financial Service India Ltd) (Investment trust of India Ltd)",
  "Udaan Capital",
  "Visu Leasing and Finance Pvt Ltd (Increed Fin)",
  "YKT Talentica India Private Ltd"
];